- name: Include project secret variables
  include_vars: "../vars/secret.yml"

- name: Prepare volume folders
  include_tasks: "tasks/volumes.yml"

- name: Docker-compose generation
  template:
    src: "../templates/compose/docker-compose.j2"
    dest: "{{ init_host_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: '0644'

- name: Init docker_compose from compose file
  docker_compose:
    project_src: '{{ init_host_path }}'
    pull: yes
    # recreate: always
    state: present
