# Provision servers
- hosts: all
  user: ansible
  become: yes
  gather_facts: yes

  tasks:

    # Date & time when starting
    - debug: msg="Starting at {{ lookup('pipe', 'date +%H:%M:%S') }} {{ lookup('pipe', 'date +%Y-%m-%d') }}"

    - name: Include init variables
      include_vars: "vars/init.yml"

    - name: Pre-install list of packages
      apt:
        name: ['apt-transport-https','ca-certificates','curl','software-properties-common', 'python3', 'python3-apt', 'python3-pip', 'htop', 'telnet']
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ansible_distribution_release}} stable

    - name: Install docker list of packages
      apt:
        name: ['docker-ce=5:19.03*', 'docker-compose=1.21*']
        state: present
        update_cache: yes

    - name: Start service cron, if not started
      service:
        name: cron
        state: started

    - name: Create init directory
      file:
        path: '{{ init_host_path }}'
        owner: root
        group: root
        state: directory
        mode: '0755'
        
    - name: Compose server web sites
      include_tasks: "tasks/compose.yml"

    - name: Install stackdriver monitoring agent
      include_tasks: "tasks/monitoring.yml"

    # Date & time when ending
    - debug: msg="Ending at {{ lookup('pipe', 'date +%H:%M:%S') }} {{ lookup('pipe', 'date +%Y-%m-%d') }}"
